sudo: false
language: ruby
rvm:
- 2.2
branches:
  only:
  - master
env:
  global:
  - GH_PAGES_REPO=axsemantics/atml3-docs
  - GH_PAGES_DOMAIN=docs.atml3.rocks
  - GH_PAGES_BASEDIR=build
cache: bundler
script: ". ./travis-deploy.sh"
